# Q.2- Name and handle the exception occurred in the following program: 
try:
	l=[1,2,3]
	print(l[3])
except Exception as m:
	print("error name is=>",m)
